### ISSUE TITLE
4.实现Web配置页面

### ISSUE THREAD

**Issue by hlleng** [wangzexi/NodeMCU-Tutorial#1]
请问一下  nodemcu配置wifi还有哪几种方式

**Comment by wangzexi** [comment]
你是说让用户配置wifi的方式？

芯片开热点，用Web来配置，应该是最方便的。
其它的，比如外接蓝牙模块之类，成本高也不方便。

**Comment by lenghonglin** [comment]
E:M 1032
not enough memory
刚直接用的您的代码和固件  也提示空间不够

**Comment by hlleng** [comment]
刚看了一下您的代码  也刷进去了，发现芯片并没有进入Ap模式  提示的是STA没连上  是我哪儿操作错误了吗

**Comment by wangzexi** [comment]
如果你是直接刷入`NodeMCU-Tutorial/4.实现Web配置页面/source/`里的全部文件的话，那么要进入**配置模式**是需要按下**配置按钮**的，详见第三篇博文接线。
