### ISSUE TITLE
能否提供一份你工程里CSS的文档

### ISSUE THREAD

**Issue by 2578893153** [wangzexi/NodeMCU-Tutorial#2]
利用你的工程基础开发，现在遇到前端的设计问题，比如我现在下拉框不知怎么去编写

**Comment by wangzexi** [comment]
> 前端方面的选择就比较多了，我使用了轻量的[Zepto.js](https://github.com/madrobby/zepto)与[Spectre.css](https://github.com/picturepan2/spectre)来搭建前端页面，通过AJAX来请求数据。
